### ISSUE TITLE
Scrum Report 1

### ISSUE THREAD

**Issue by betternick** [tendy-s/OutDoorly#1]
**Each individual needs to post their scrum report as a comment on this issue:**

**Questions your comment should answer:
1. What did you work on this past iteration (2 weeks)? 
2. What were any major issues/challenges you ran into? 
3. What do you plan to work on for this coming iteration (2 weeks)?** 

_Rubric:
2: Includes all 3 points. Demonstrates a bit of meaningful reflection on at least one item in the report.
1: Simplistic, or no meaningful, specific information.
0: Missing or Late._

**Comment by babakhadady** [comment]
Name: Babak Hadady
csid: y9m6h

1. This iteration we solidified a project idea, came up with a general outline and wrote some vague project requirements that we will definitely implement, and stretch requirements that we will consider depending on how the term proceeds. We also divided up workflow and assigned general position to everyone.

2. We found it difficult to come up with a project idea initially, because we all came up with many possibilities and we were developing them as we continued to come up with ideas. We ended up voting on a few ideas and that helped solidify what we would chose as for project.

3. We plan on developing our requirements into more concrete user stores and evolving what endpoints our backend will support. We will also implement some initial components and further solidify our tech stack / development process. I will investigate deeper into DevOps processes to integrate into our project, and begin working on some React Components.

**Comment by tendy-s** [comment]
Name: Tendy Su 
csid: f7p0u

 1. What did you work on this past iteration (2 weeks)? 
     I worked on collaborating with my group members to brainstorm ideas and requirements for our project, and improving my skills in HTML, CSS and JavaScript. 

2. What were any major issues/challenges you ran into? 
    In the beginning it was definitely challenging for us to agree on a project idea, but we were able to resolve the issue by merging a couple of ideas and building on top of one another’s suggestions.

3. What do you plan to work on for this coming iteration (2 weeks)? 
    For the next 2 weeks, I will help build out the skeleton of our UI (connect the screens and establish a basic workflow), more concretely define the various components in our app and work on completing and styling at least one main component (e.g. the form for collecting user preferences) with React, SASS and MaterialUI. I will also do more self-learning on Redux and research on our National Parks US API to see what are the relevant information we would need.

**Comment by betternick** [comment]
Name: Syed Ahmed (CSID: a2o6b)

In the brainstorming phase, each member suggested a project idea. We voted to select one. We then exchanged ideas on implementation, technical challenges and tentative roles for team members.

Initially we struggled with deciding on an idea. We also struggled with assigning work roles since we wanted broad exposure to the MERN stack and not to be too specialized/sequestered into a single role.

We will start designing the frontend and backend, further refine our website requirements, and start making user stories.

**Comment by dong-michael** [comment]
Name: Michael Dong
CSID: f2m2e

1. What did you work on this past iteration (2 weeks)?

In this iteration, I worked closely with my teamates to come up with and decide on a project topic for the term. In addition, we also completed the project progress report and discussed at a high level of how the project can implemented and how we should divide the work.
  
2. What were any major issues/challenges you ran into?

Although there were some struggles in deciding how the work should be divided between group members, we were able to come to a conclusion where tentative roles were assigned to everyone, with the possibility for change so that all team members could get exposure to working on different aspects of the project. 

3. What do you plan to work on for this coming iteration (2 weeks)?**

In the coming iteration, we will refine our requirements under a finer lens and begin the process of designing our website architecture. I will also do some self learning on MongoDB and will also be providing support to my teammates wherever required.

**Comment by h-xi** [comment]
Name: Has (Hai Xin) Xi
CSID: Z3J4E
1) This week I worked with my team to come up with project ideas. I researched into building CI/CD pipelines + mongoDB best practices. 
2) The team had some initial struggles with coming up with a project idea + dividing up work amongst the group members. We were able to figure out a process that we believe will work for our development cycles after some deliberation. 
3) System design, database design, backend endpoints (controller + router logic)
